### ISSUE TITLE
slug for search_queries

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#149]
It probably is a good idea to add a `slug` field to the `search_queries` resource. So that they are not addressed by an `id` but the `slug`. The `slug` should be related to `value`. I have no exact idea how this is done best.

**Comment by cjfreeze** [comment]
This is definitely an interesting issue, as `search_queries` are case sensitive, and can contain html unsafe text. Ecto allows you to just set any value as the "data value" of a schema, so when that schema is passed as a html parameter, phoenix uses that indicated field as the data for the request. By default, it's the `id`, but for example with `User` it's the `active_slug` field. However since `search_queries` can contain html unsafe text it's inconvenient to just use `value` as the slug.

It might just be best to create a `slug` field like in `User`, but I'll put some thought into it before I decide on a path. Let me know if you have a way you prefer.

**Comment by wintermeyer** [comment]
`seach_queries` should not contain html unsafe text. I don't see a reason why it should. Anyway: I like the idea of doing something similar to the way we do it for `User`.

PS: It should be downcased.
