### ISSUE TITLE
Flash messages do not work on index when no user is logged in.

### ISSUE THREAD

**Issue by cjfreeze** [wintermeyer/vutuv#196]
This is most noticeable when a user creates an account. Normally a flash message should appear, but flash messages are stored in the session, which we drop to prevent cookies. The user is left with no instructions regarding the email they will then receive.

Storing them server side is a potential memory leak. They have to be stored in the session. As a temporary fix, I am changing the `manage_cookies` plug to not drop the session if it detects a flash in the session, as well as if the user is logged in.

**Comment by wintermeyer** [comment]
- When a user creates a new account he/she accepts that we use cookies. So your solution is fine.
- In addition please have a look at https://github.com/vutuv/vutuv/commit/280ae5a419028e7f1947e17d51925c5909b11414 
  => I changed the workflow so that a `users#create` will lead to a different page. I feel that this is easier to understand for a new user than to have the same index page again.
