### ISSUE TITLE
Feedback Button

### ISSUE THREAD

**Issue by stephriedel** [wintermeyer/vutuv#362]
Als Anwender möchte ich einen gut sichtbaren Feedback Button in vutuv nutzen um Anregungen und Fehlermeldung zu reporten

**Comment by wintermeyer** [comment]
Danke für den Input. Das mit dem gut Sichtbar ist gar nicht so einfach. Aktuell haben wir einen Link im Footer. Ich werde das mal im nächsten Team Meeting ansprechen. Fürs erste schliesse ich das Issue.

@all: @stephriedel asks for a feedback button which is prominently displayed. So that the user can easily share feedback with us. I answered that prominently is not easy to do but that we have the link in the footer. Lets discuss it again down the road.

**Comment by stephriedel** [comment]
Ok danke; hmmm vergessen - schreibe die kommenden "Ideen" in Englisch ;-)

Am 22.11.2016 um 16:50 schrieb Stefan Wintermeyer:
