### ISSUE TITLE
Social Media Accounts should be unique

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#440]
### Expected behavior

A social media account should be unique. If somebody try to create an already existing social media account he/she should get a warning flash message with a link to the user who already has it.

**Comment by cjfreeze** [comment]
Interesting obstacle to this: Phoenix uses a `safe` typing when embedding things in a template. Anything not `safe` will be escaped, so you can't have functional html in a function translate to the template without first making sure you mark it as `safe`. I use this is several locations, such as the `Pages` page link helper function. However all form errors are automatically run though `gettext`, and it just so happens that `gettext` doesn't expect to receive `safe` tuples rather than plain binaries, preventing me from embedding an `<a>` element in the error message. Right now I have the error message saying `Someone has already claimed this account`

What this boils down to is I either implement a very hackish solution to bypass the existing error helpers in this specific case, or I spend a lot of time investigating a solution that works elegantly. Either way, I'm creating a 1.2 issue for the second half of this issue (#446). There were no problems encountered making social media accounts unique, just make sure there are no duplicate accounts in the database before the migration, or else you'll have problems.
