### ISSUE TITLE
Footer behaves strange

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#444]
Please have a look at the following screenshots (both made on a macOS). The footer is off.

# Safari

![bildschirmfoto 2016-11-25 um 14 46 43](https://cloud.githubusercontent.com/assets/69770/20627092/2b10cc48-b31e-11e6-9a3a-d839606ce793.png)

# Chrome

![bildschirmfoto 2016-11-25 um 14 47 06](https://cloud.githubusercontent.com/assets/69770/20627095/2fb94234-b31e-11e6-972a-0050565822b1.png)

**Comment by cjfreeze** [comment]
@wintermeyer Is it possible to have the css guys take a look at this

**Comment by DerLordi** [comment]
I analysed the problem.

The footer bar is placed 0px absolutley from the bottom. The element which the footer is relatively positioned from, is the body - tag (the nearest parent element with the style: position: relative). So it stays always absolutley 0 px from the bottom of the height of the body - tag. 

The height of the body is calculated by the content within (the left side of the page). The aside - tag aka. sidebar, is also positioned absolute 20px from the right side to the body - tag. Absolute positioned elements are removed from the html flow, thus are not considered for the height calculation of the parent element. They are free floating elements on the site. 

**So if the sidebars height is greater then the height of the main content, the described bug occurs, because it is only "attached" to the body tag.**

There is no clean way to fix this issue with the css at hand. There are terrible terrible hacks out there for this problem, or just adding the height with javascript to the parent element. But neither of both methods should be added in this project. 

So i suggest to change the way both elements are positioned. I will try evaluate a solution that puts the sidebar in the correct position with another methods. At the moments this is just an idea.
