### ISSUE TITLE
Display skills on less real estate

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#453]
### Expected behavior
Skills should take less space without looking too crowded either. I have no idea how to solve this. The first thing which come to mind is to display it in two columns. But I don't even know if this is a good idea at all. Everybody talks about white space. So maybe we shouldn't change it at all.

### Actual behavior
They take a lot of real estate with comparable little information.

![bildschirmfoto 2016-11-27 um 16 09 59](https://cloud.githubusercontent.com/assets/69770/20649284/2e993e32-b4bc-11e6-8ca1-62ce3a145105.png)

**Comment by xamiam** [comment]
Hey Stefan,

Wouldn't use two columns, because the top-down order matters. How about using floats for upvotes and bars? I guess the relative width of the bars depends on the upvotes, right?

Like so:

SKILL
x upvotes  ##########################
SKILL
x upvotes  ###################
SKILL
x upvotes  ############

yours,

max.

**Comment by wintermeyer** [comment]
Here is @xamiam's demo screenshot:

![vutuv_upvotes_mm](https://cloud.githubusercontent.com/assets/69770/20664733/d297af8c-b55c-11e6-9e7d-da919e6fb101.png)

**Comment by wintermeyer** [comment]
I like the idea. @xamiam: Can you provide us with the CSS for this? @cjfreeze Are there any side effects by changing the buttons. These once are more edgy.
