### ISSUE TITLE
Add redirect to entry point ("/")

### ISSUE THREAD

**Issue by riverrun** [wintermeyer/vutuv#591]
When users access the root url, they should be redirected to their own page, if there is a cookie present, or the new users / signup page.

**Comment by wintermeyer** [comment]
No need for the redirect to the new users sign up page for people without a cookie. The root url will be the sign up page.

**Comment by riverrun** [comment]
At the moment, we have a `users/new` route, which would provide the signup functionality. Shall we move that logic (controller function, etc.) to the root url?

**Comment by wintermeyer** [comment]
> At the moment, we have a `users/new` route, which would provide the signup functionality. Shall we move that logic (controller function, etc.) to the root url?

Can we keep the logic there but tell the router to use it too for the root url? Does that work?

Reasoning: I don't want a redirect for new users. Speed is paramount and a redirect takes that away. That's ok for already signed in users but new users have to get the quickest possible answer. But I don't like to move logic form `users/new` because I think that this is the proper location. But if it's only possible by moving than we have to move it to the root url.

**Comment by riverrun** [comment]
Ok. I'll look into it and get back to you soon.

**Comment by riverrun** [comment]
Setting the root url to the new function in the user controller works.

I have two related questions:

* after a user logs in, should they be redirected to their own page (show page) or the users index page?
* do we need the users index page (which is meant to list users)

**Comment by wintermeyer** [comment]
> * after a user logs in, should they be redirected to their own page (show page) or the users index page?

Their own page.

> * do we need the users index page (which is meant to list users)

Good question. I want to say yes. For Google.

**Comment by riverrun** [comment]
Ok. Got it.
