### ISSUE TITLE
Check for not so good passwords

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#623]
A thought: Wouldn't it be a good thing if we tell people that their password is not safe?

We could use the hashed from
https://haveibeenpwned.com/Passwords
to check against. If a password is not secure we'd ask the user to enter an other one.

I don't know how to implement this UX workflow wise. It is just a thought.

**Comment by wintermeyer** [comment]
Second thought: As much as I don't want people to use bad passwords I don't want to be their parent either. Who am I to judge?! So maybe a good compromise would be to tell users in the first email that their used password is not secure because it has be used by x number of other people (which we can check with the data from https://haveibeenpwned.com/Passwords) and add a link to https://haveibeenpwned.com and a link to the place where they can change their password within vutuv.

**Comment by riverrun** [comment]
I maintain a [password checker](https://github.com/riverrun/not_qwerty123) that we could use on the backend when checking the new user details. Using this, the feedback should be fairly quick, but in the future, we could also consider using a frontend solution if we want something more user-friendly.

I think it's important to check password strength because if there is a data breach, no password hashing function can protect weak passwords - they will very quickly be cracked.

**Comment by riverrun** [comment]
Fixed in #647
