### ISSUE TITLE
Manage new email addresses

### ISSUE THREAD

**Issue by riverrun** [wintermeyer/vutuv#625]
## Problem

As mentioned in #620, many users do not enter their email addresses correctly. This means that unless these email addresses are managed correctly, there will be many incorrect email addresses store in the database and registered to users.

## Solution

Add a process that manages email addresses: when an email address is created, this email management process will be notified that we are awaiting email confirmation. If the email address is created, the email value will be removed from this process's state. If there is no confirmation within the time limit, further action will be taken. Initially, this further action will be that the email address will be removed from the database, but in the future, we could send a reminder to the user before deleting it.

## Additional information

Although we will be implementing stricter email validation, as stated in #620 comments, there will still be incorrectly input email addresses that we will need to deal with, and that is why we will need this additional process.

**Comment by wintermeyer** [comment]
In the long term it would be useful to pipe sendmail/postfix error emails from into this workflow. So when we get an error message from postfix that this email address doesn't exist we can mark it accordingly.

Unfortunately we can not mark it as unfit for ever because there is the chance that it will become an active email address in the future.

Probably deleting those uses with a cron job once a day is the best way to go.

**Comment by riverrun** [comment]
Added in #628
