### ISSUE TITLE
Name fields - needs and uses

### ISSUE THREAD

**Issue by riverrun** [wintermeyer/vutuv#633]
According to [this article about making more inclusive forms](https://www.uxbooth.com/articles/creating-more-inclusive-and-culturally-sensitive-forms/) and [this article which argues for only having one name field](https://uxmovement.com/forms/why-your-form-only-needs-one-name-field/), many users are left out when asked to fill in forms with the traditional 'First name' and 'Last name' fields. In addition, we have 3 fields for the name, and I think the users will find it easier if we just offer them one - a 'Full name' field.

Also, we are asking users for their 'Nickname', which seems a little too informal. I think we should consider using 'Preferred name' instead. Of course, this does also depend on how this information is used, but I think that 'Preferred name' is more suitable.

Any thoughts?

**Comment by panomaki** [comment]
I think there are a couple of issues to be solved here which have to do with the usage of the field. The first of which is that if it is used to find people, it should be designed to allow for all ways in which people are known, including first name, last name and nickname, This *could* be saved in one field, if the search algorithm is designed appropriately. Second is the way in which people would like to be addressed, which may or may not be related to what is saved in the name-field mentioned earlier. This may be a more formal addressation - Dr Wossname, Daniel-San, Weledelgestrenge heer Woudstra, etc. There may be possibilities in localization/i8n environments to address this, but it's not my field of knowledge. It may also be an informal addressation - nickname, only firstname, or whatever. So two more fields - ah, you have three already ;-). One for name, one for formal addressation, one for informal addressation?

Just 2 cents for the discussion...

**Comment by wintermeyer** [comment]
**First of all: Great issue!** That's the kind of discussion I really enjoy. I think that we have to do a better job with this than LinkedIn or XING. That said: I've been thinking about this for the last 20 something hours and haven't found a one-size-fits-all answer.

The reason why we started with `first_name`, `last_name` and `gender` is that this gives us the possibility to create a proper greeting in an email. In German an email would start with "Hallo Herr Wintermeyer," or "Sehr geehrter Herr Wintermeyer," (more formal) but a "Hallo wintermeyer," (account name) would be rude. A "Hallo Stefan Wintermeyer," shouts out loud "we didn't know what gender you are and therefor we do this". A "Hallo Stefan," doesn't go well in German either because that would be a little too less formal (at least for the elder generation).

So for Germany and many other countries this would be the best way to go. But I realize that the world is bigger and that we want to be as inclusive as possible. 

So maybe we really should start with just `full_name`, `email_address` and `country` (drop-down?) in our sign up form. We could use a service like https://gender-api.com to auto separate the `full_name` in Countries where we feel save that this is a good idea (e.g. Germany). Of course such an API is not a 100% solution but 80% is better than nothing.

users could change their `gender`, `first_name` and `last_name` anytime. We could tell them in the first email that we tried to autofill these fields and asks them to double check.

If nobody comes up with a better idea I say: Let's start with `full_name`, `email_address`, `city` and `country` in the sign up page. With a presence validation on `full_name` and `email_address`. Than we do a white list of countries where we use https://gender-api.com to auto split `full_name`. For all others we just keep the `full_name` but give the user the option to fill out the other fields in the users#edit form.

**Comment by riverrun** [comment]
In #635, I changed the first_name, last_name and middlename fields to full_name, and I changed the nickname field to preferred_name.

I will keep this issue open, as there is plenty to discuss, especially with regard to how we want to use the name fields.

**Comment by oliverandrich** [comment]
Going for a single `full_name` field is the best solution. But I like to ask why you actually want to store gender information in your database? Is it essential for vutuv? I mean, it is not a dating platform and it is a wide field with a lot of tough discussions. Personally, I would forget about the gender and try to solve the addressing issue in emails with a gender neutral wording.

**Comment by wintermeyer** [comment]
> Going for a single `full_name` field is the best solution.

I agree on that but I'd like to have a `first_name` and `last_name` field in addition for people like myself who care about how it is used.

> But I like to ask why you actually want to store gender information in your database? Is it essential for vutuv?

Gender is part of many greetings. I want to be able to greet people accordingly to their culture. This might not be needed always or at the beginning but I want to have that information to be able to do it.

That said: I also want to have a "diverse" field as we have in version 1.x. I don't want to force users to have to choose between "male" and "female".

<img width="500" alt="Bildschirmfoto 2019-06-09 um 11 20 56" src="https://user-images.githubusercontent.com/69770/59157309-bce87300-8aa8-11e9-8934-84130053df72.png">

**Comment by riverrun** [comment]
Regarding first name and last name, we should be able to calculate these from the full name. However, I think we also need to research how users view different greetings, questions, etc., and then base our decision(s), at least partly, on that research.

**Comment by wintermeyer** [comment]
@riverrun About the research: That would be optimal. But for now let's make educated guesses for this. I'll take care about the German speaking part of the world and you take care about the English speaking part. We try to be as generic as possible for the rest.

I kind of hope that open-source will be a good way of adding other cultures here.

**Comment by riverrun** [comment]
Let's close this issue for now. If we have any further comments, we can reopen it later.
